config/routes.rb
Phonenote::Application.routes.draw do
  resources :blogs

  resources :users

  resources :notes
  
  resources :sessions , only:[:new , :create, :destroy]
  match '/signin' , to: 'sessions#new'
  match '/signout' , to: 'sessions#destroy' , via: :delete
  match '/index' , to: 'homes#index' 

  get "/homes/announcement"

   root :to => 'homes#index'

end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  phone      :integer
#  email      :string(255)
#  qq         :integer
#  skype      :string(255)
#  name       :string(255)
#  job        :string(255)
#  tel        :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# before_filter :admin_user, only: [:destroy , :edit, :update] 
class Note < ActiveRecord::Base
  attr_accessible :email, :job, :name, :phone, :qq, :skype, :tel
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :signed_in_user, only: [:edit , :update] 
  before_filter :current_user, only: [:edit , :update] 
  before_filter :admin_user, only: :destroy 
  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_path, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :姓名 %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :手机 %><br />
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :邮箱 %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :qq %><br />
    <%= f.number_field :qq %>
  </div>
  <div class="field">
    <%= f.label :skype %><br />
    <%= f.text_field :skype %>
  </div>
  <div class="field">
    <%= f.label :职务 %><br />
    <%= f.text_field :job %>
  </div>
  <div class="field">
    <%= f.label :分机号 %><br />
    <%= f.number_field :tel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<div class="container_24">
    <h3 class="page-header">通讯录</h3>
    <% if current_user && current_user.admin == true %>
    <%= link_to '创建新成员', new_note_path , :class=>'btn btn-primary goright' %>
    <% end%>
<table class="table tabletop">
  <tr>
    <th>姓名</th>
    <th>手机</th>
    <th>邮箱</th>
    <th>QQ</th>
    <th>Skype</th>
    <th>职务</th>
    <th>分机号</th>
    <% if current_user && current_user.admin == true %>
        <th></th>
        <th></th>
    <% end%>
  </tr>

<% @notes.each do |note| %>
  <tr>
    <td><%= note.name %></td>
    <td><%= note.phone %></td>
    <td><%= note.email %></td>
    <td><%= note.qq %></td>
    <td><%= note.skype %></td>
    <td><%= note.job %></td>
    <td><%= note.tel %></td>
    <% if current_user && current_user.admin == true %>
        <td><%= link_to '编辑', edit_note_path(note) %></td>
        <td><%= link_to '删除', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end%>
  </tr>
<% end %>
</table>

<br />

app/views/notes/new.html.erb
<div class="container_24">
<%= render 'form' %>

<%= link_to 'Back', notes_path , :class => "btn" %>
</div>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Phone:</b>
  <%= @note.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @note.email %>
</p>

<p>
  <b>Qq:</b>
  <%= @note.qq %>
</p>

<p>
  <b>Skype:</b>
  <%= @note.skype %>
</p>

<p>
  <b>Name:</b>
  <%= @note.name %>
</p>

<p>
  <b>Job:</b>
  <%= @note.job %>
</p>

<p>
  <b>Tel:</b>
  <%= @note.tel %>
</p>


<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>