config/routes.rb
Phonenote::Application.routes.draw do
  resources :blogs

  resources :users

  resources :notes
  
  resources :sessions , only:[:new , :create, :destroy]
  match '/signin' , to: 'sessions#new'
  match '/signout' , to: 'sessions#destroy' , via: :delete
  match '/index' , to: 'homes#index' 

  get "/homes/announcement"

   root :to => 'homes#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  usertype        :integer          default(1)
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  remember_token  :string(255)
#
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :usertype , :admin
  has_secure_password
  validates :name , presence: true, length:{ maximum:40 }
  validates :email , presence: true
  validates :password , presence: true , length: { minimum: 6 }
  validates :password_confirmation , presence: true 
  has_many :blogs
  has_many :avatars , :as => :avatar_for
  before_save :create_remember_token
  before_save{ |user| user.email = email.downcase }
  
  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit , :update] 
  before_filter :current_user, only: [:edit , :update] 
  before_filter :admin_user, only: :destroy 
    include SessionsHelper
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        Avatar.create(:avatar => params[:avatar] , :avatar_for => @user)
        sign_in @user
        flash[:success] = "注册成功，欢迎来到卓衡科技"
        format.html { redirect_to @user }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        Avatar.create(:avatar => params[:avatar] , :avatar_for => @user)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
		gravatar_id=Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url , class:"gravatar")
    end
end

app/views/users/_form.html.erb
<%= form_for(@user,:html => {:multipart => true} ) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if current_user && current_user.admin == true %>
   <%= f.radio_button :admin, true %> 提升为管理员
  <% end %>

  <div class="field">
    <%= gravatar_for @user %>
    <%= f.label :用户名 %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :邮箱 %><br />
    <%= f.text_field :email %>
  </div>
  <% if current_user.id == @user.id%>
  <!-- <a class="change_passwd_link">修改密码</a> -->
  <div class="passwd_area">
      <div class="field">
        <%= f.label :密码 %><br />
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label :重复密码 %><br />
        <%= f.password_field :password_confirmation %>
      </div>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= file_field_tag :avatar %>
  </div>
  <% end %>
  <div class="actions">
     <input type="submit" value="提 交" class="btn btn-primary">
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
<h3>编辑用户信息</h3>

<%= render 'form' %>

<%= link_to '详情', @user %> |
<%= link_to '返回', notes_path %>
</div>

app/views/users/index.html.erb
<div class="container">
<h3>用户列表</h3>

<table>
  <tr>
    <th>Type</th>
    <th>Name</th>
    <th>Admin</th>
    <th>Email</th> 
    <th>Password digest</th>
    <th>Remember_token</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.usertype %></td>
    <td><%= user.name %></td>
    <td><%= user.admin %></td>
    <td><%= user.email %></td>
    <td><%= user.password_digest %></td>
    <td><%= user.remember_token %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '创建新用户', new_user_path , :class=> "btn btn-primary" %>
</div>

app/views/users/new.html.erb
<div class="container">
<h3>用户注册</h3>

<%= render 'form' %>

<%= link_to '返回', users_path %>
</div>

app/views/users/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <b>用户名:</b>
  <%= gravatar_for @user %>
  <%= @user.name %>
</p>

<p>
  <b>E-mail:</b>
  <%= @user.email %>
</p>


<%= link_to '编 辑', edit_user_path(@user) %> |
<%= link_to '返 回', notes_path %>
</div>