config/routes.rb
Phonenote::Application.routes.draw do
  resources :blogs

  resources :users

  resources :notes
  
  resources :sessions , only:[:new , :create, :destroy]
  match '/signin' , to: 'sessions#new'
  match '/signout' , to: 'sessions#destroy' , via: :delete
  match '/index' , to: 'homes#index' 

  get "/homes/announcement"

   root :to => 'homes#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phonenote</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="navbar">
      <div class="navbar-inner">
          <div class="container_24">
              <%= link_to '卓衡科技内部交流薄', "/" , :class=> "brand" %>
            <ul class="nav">
              <li><%= link_to '通讯录', notes_path %></li>
              <li><%= link_to 'BLog', blogs_path %></li>
              <li><%= link_to '公告', "/homes/announcement" %></li>
              <% if current_user && current_user.admin == true %>
              <li><%= link_to '用户', users_path %></li>
              <% end %>
            </ul>
            <div class="useradmin">
                <% if signed_in? %>
                <%= link_to current_user.name , edit_user_path(current_user) %>
                 <% if current_user && current_user.admin == true %>
                 <span>（管理员）</span>
                 <% end %>
                <%= link_to '注销' , signout_path , method: "delete" %> 
                <% else %>
                <a class="login_index" data-toggle="modal" href="#myModal">登陆</a> 
                | <a class="regist_index" data-toggle="modal" href="#myregist">注册</a>
                <% end %>
            </div>
        </div>
      </div>
    </div>
    <div class="container">
        <% flash.each do |key , value|%>
            <div class="alert alert-<%= key%>"><%= value%></div>
        <% end %>
    </div>
    
    <div id="myregist" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">注 册</h3>
      </div>
      <div class="modal-body">
          <%= form_for User.new, :html => {:multipart => true} do |f|%>
              <pre>
                  用 户 名：<input name="user[name]" type="text"/>
                  邮    箱：<input name="user[email]" type="email"/>
                  密    码：<input name="user[password]" type="password"/>
                  重复密码：<input name="user[password_confirmation]" type="password"/>
              </pre>
               <input type="submit" value="注 册" class="btn btn-primary">
          <% end %>
      </div>
    </div>
    
    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">登 陆</h3>
      </div>
      <div class="modal-body">
          <%= form_for(:session , url: sessions_path) do |f|%>
              <pre>
                  邮  箱：<input name="session[email]" type="email"/>
                  密  码：<input name="session[password]" type="password"/>
              </pre>
              <input type="submit" value="登 陆" class="btn btn-primary">
          <% end %>
      </div>
    </div>

<%= yield %>

</body>
</html>